### ISSUE TITLE
mysql问题

### ISSUE THREAD

**Issue by Android-Dongyf** [cloudfreexiao/RillServer#9]
前言
1、感谢作者提供代码，让小白也能够开始玩游戏服务了
问题
1、测试demo相关的例子已经不能完成正常测试，需要自行修改才能跑通，作者还准备维护吗？
2、麻烦提供下mysql数据库下  各数据库表的创建sql

**Comment by cloudfreexiao** [comment]
不好意思 我不用 mysql
